# Generated by Django 5.1.5 on 2025-04-21 05:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizresult",
            name="set",
        ),
        migrations.RemoveField(
            model_name="quizresult",
            name="user_id",
        ),
        migrations.AddField(
            model_name="quiz",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="quiz",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="quiz",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="lms.quiz",
            ),
        ),
        migrations.AddField(
            model_name="quizresult",
            name="quiz",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="lms.quiz"
            ),
        ),
        migrations.AddField(
            model_name="quizresult",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lms.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="choice_a",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="choice_b",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="choice_c",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="choice_d",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="question_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="subject_code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lms.module",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="total_questions",
            field=models.IntegerField(default=20),
        ),
        migrations.AlterModelTable(
            name="questionbank",
            table="lms_questionbank",
        ),
    ]
