# Generated by Django 5.1.5 on 2025-04-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_remove_quizresult_set_remove_quizresult_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizresult",
            name="set_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
