# Generated by Django 5.1.5 on 2025-04-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_remove_quizresult_set_remove_quizresult_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="total_questions",
            field=models.IntegerField(default=20),
        ),
    ]
