# Generated by Django 5.1.5 on 2025-04-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_quizresult_set_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizresult",
            name="cluster",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="quizresult",
            name="percentage",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="quizresult",
            name="total_questions",
            field=models.IntegerField(null=True),
        ),
    ]
