# Generated by Django 5.1.5 on 2025-04-21 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_quizresult_cluster_quizresult_percentage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizresult",
            name="set_id",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="quizresult",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lms.userprofile",
            ),
        ),
    ]
