# Generated by Django 5.1.5 on 2025-04-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_alter_quizresult_set_id_alter_quizresult_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_id",
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
