# Generated by Django 5.1.5 on 2025-04-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0006_alter_course_course_id_alter_course_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="module_id",
            field=models.CharField(max_length=50),
        ),
    ]
