# Generated by Django 5.1.5 on 2025-04-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0007_alter_module_module_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="quiz_id",
            field=models.CharField(max_length=50),
        ),
    ]
