# Generated by Django 5.1.5 on 2025-04-22 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_alter_quiz_total_questions"),
        ("lms", "0008_alter_quiz_quiz_id"),
    ]

    operations = []
