# Generated by Django 5.1.5 on 2025-04-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0009_merge_20250422_1128"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(default="Unknown", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="login_id",
            field=models.CharField(default="unknown", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="position",
            field=models.CharField(default="Unknown", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User"), ("manager", "Manager")],
                default="user",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="staff_id",
            field=models.CharField(max_length=20),
        ),
    ]
